language: node_js

node_js:
  - 'stable'
  - '6'

sudo: false

before_install:
  - if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key: $NPM_TOKEN
    on:
      tags: true
      node: '6'
    skip_cleanup: true
